Initial draft for define data elements
jiabingeng/places-service-docs pull request #14
Opened 2019-10-23 19:48 UTC by phuo1032

2019-10-23 22:32 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +Data elements are the building blocks for the applications data dictionary and are used to collect, organize, and deliver data across marketing and ad technology.
- Please add an apostrophe in "applications" --> "application's".

2019-10-23 22:33 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +With Places extension, you can reference values from the following targets:
Please add "the" between "With" and "Places"

2019-10-23 22:34 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +* Current POI, which refers to the POI in which your customer is currently located. If the user is located in multiple POIs, the one belongs to the library with higher rank is picked. If multiple POI
Please move the content starting with the 2nd sentence down one line and line it up with the bullet. It should look like this:
"* Current POI, which refers to the POI in which your customer is currently located. 

    If the user is located in multiple POIs, the one belongs to the library with higher rank is picked. If multiple POIs belong to the highest rank library, the one with the smallest radius is picked.

2019-10-23 22:34 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +Each POI contains the following data references
Please add a colon (:) after "references"

2019-10-23 22:37 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +1. From a Property page, open the Data Elements tab.
Please change "From a Property page" to:
"In the Property page for your app, click the **Data Elements** tab.

2019-10-23 22:41 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +![Create DE 2](../.gitbook/assets/create-de-2.png)
please remove image link, not necessary

2019-10-23 22:42 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +3. From the extension menu, select Places.
Please reword to:
"3. In the list of installed extensions, find Places."

2019-10-23 22:43 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +![Create DE 3](../.gitbook/assets/create-de-3.png)
please remove image link, not necessary

2019-10-23 22:44 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +4. From the Data Element Type drop-down list, select a data reference for this data element.
Please reword to 
"4. In the **Data Element Type** drop-down list, select a data reference for this data element."

2019-10-23 22:45 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +![Create DE 4](../.gitbook/assets/create-de-4.png)
please remove image link, not necessary

2019-10-23 22:45 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +![Create DE 5](../.gitbook/assets/create-de-5.png)
please remove image link, not necessary

2019-10-23 22:45 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +![Create DE 6](../.gitbook/assets/create-de-6.png)
please remove image link, not necessary

2019-10-23 22:45 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +![Create DE 7](../.gitbook/assets/create-de-7.png)
please remove image link, not necessary

2019-10-23 22:45 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +6. If this data element is a custom metadata reference, pick a metadata key.
Please replace "pick" with "select"

2019-10-23 22:46 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +7. Type a name for the data element, and click Save .
Please remove the comma, put "Save" in bold, and remove the extra space between "Save" and the period. Should look like this:
"7. Type a name for the data element and click **Save**.

2019-10-23 22:48 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +After a data element is created, you can use it from any rule component if a data element picker is present.
Please reword as follows:
"After a data element is created, if a data element picker is present, you can use the data element from any rule component."

2019-10-23 22:49 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +![Use DE 1](../.gitbook/assets/use-de-1.png)
please remove the 2 image links...not necessary

2019-10-23 22:50 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +If a data element picker is not present in the rule component, you may still use the data element by wrapping the data element name with the **%%** tokens.
Please replace "may still" with "can"

2019-10-23 22:50 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +For example, if the data elmement name is **Last POI City**, you may add **%%LAST POI City%%** to a text input.
Please remove "may" and replace with "can"

2019-10-23 22:51 UTC, rekrishn commented on places-launch-rules/define-data-elements.md
> +If data elements are used in any of the rule components. They must also be included in the library and published.
The first sentence is not a complete sentence. It looks like the 2 sentences should be combined like this:
"If data elements are used in any of the rule components, these data elements must also be included in the library and published."

2019-10-23 22:52 UTC, rekrishn requested changes
some changes @phuo1032...let me know if you have any questions.

2019-10-23 23:20 UTC, phuo1032 commented
@rekrishn I updated the text as requested. I think the screenshots are helpful for customers to onboard quickly, even with the cost of adding difficulties to localize later. Also, Launch is not localized so the screenshot will pretty much be the same.

Let's get some input from others to see what they think.

2019-10-23 23:34 UTC, rekrishn commented
> @rekrishn I updated the text as requested. I think the screenshots are helpful for customers to onboard quickly, even with the cost of adding difficulties to localize later. Also, Launch is not localized so the screenshot will pretty much be the same.
> 
> Let's get some input from others to see what they think.

2019-10-28 20:31 UTC, rekrishn approved these changes
looks good @phuo1032, thanks!

2019-10-28 20:31 UTC, merged